name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          echo "Hello, world!"
      
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:    
         server_address: smtp.163.com
         server_port: 465
#          server_address: smtp.gmail.com
#          server_port: 465
         username: ${{ secrets.MAILUSERNAME }}
         password: ${{ secrets.MAILPASSWORD }}

         subject: mmmmmm
         to: ${{ secrets.MAIL_LIST }}
         from: GithubActions
         secure: true
         body:  |
           Build job ( ${{ github.job }} ) of ${{ github.repository }} completed successfully! 
           Commit msg: ${{ github.event.head_commit.message }}
         ignore_cert: true
         priority: low
